name: daily-fear-and-greed-cron-job
on:
  schedule:
    - cron: '*/3 * * * *'
  push:
    branches: [ main ]
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: daily-fear-and-greed-cron-job
        run: |
          curl --request POST \
          --url 'https://notefinity.vercel.app/api/fear-and-greed' \
          --header 'Authorization: Bearer ${{ secrets.PUSHSAFER_API_KEY }}'
